import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { parseHTML } from 'linkedom';
import { renderer, contextFromFiles, decorate } from '../scripts/admin/render.mjs';
import { parseSource, setValue } from '../scripts/admin/document.mjs';
const bundle=JSON.parse(fs.readFileSync('assets/admin/context.json','utf8'));const site=contextFromFiles(bundle),render=renderer(bundle);
for(const project of site.projects){test('real template renders preserved blocks: '+project.path,async()=>{const file=bundle.files[project.path],p=parseSource(file.source,project.path);const result=await render(site,project.path,file.source);const{document}=parseHTML(result.html);assert.equal(document.querySelector('.project-heading h1').textContent,p.data.title);assert.equal(document.querySelectorAll('.project-opening .content-block').length,p.data.opening_sections?.length||0);assert.equal(document.querySelectorAll('.project-body .content-block').length,p.data.sections?.length||0);assert.equal(document.querySelectorAll('.hero-carousel-slide').length,p.data.interactive_map||p.data.structure_lab?0:p.data.hero_gallery?.length||0);decorate(document,project.path,p.data,p.body);assert.equal(document.querySelector('.project-heading h1').dataset.editPath,'["title"]');const body=document.querySelector('.project-context, .studio-project-context');assert.equal(body.dataset.editPath,'["$body"]');for(const el of document.querySelectorAll('[data-edit-path]'))assert.ok(Array.isArray(JSON.parse(el.dataset.editPath)));});}
for(const key of Object.keys(site.data)){if(!bundle.files['_data/'+key+'.yml'])continue;test('page data real template: '+key,async()=>{const path='_data/'+key+'.yml';const result=await render(site,path,bundle.files[path].source);assert.ok(result.html.includes('<html'));assert.ok(!result.html.includes('[object Object]'));});}
test('new title changes preview without altering blocks',async()=>{const project=site.projects.find(p=>p.sections?.some(s=>s.type==='media-row'));const file=bundle.files[project.path];const next=setValue(file.source,project.path,['title'],'Changed in preview');const result=await render(site,project.path,next);assert.match(result.html,/<h1>Changed in preview<\/h1>/);assert.deepEqual(parseSource(next).data.sections,parseSource(file.source).data.sections);});
test('publication renders in real publications page',async()=>{const p=site.publications[0];const result=await render(site,p.path,bundle.files[p.path].source);assert.ok(result.html.includes(p.title.replaceAll('&','&amp;')));});
