/* Explanations use the same state and source rows as the model and PDF reader. */
(function(root){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:d}):'—';
const labels=['Model condition','Find the row and column','What the value means','What changes in the model'];
const card=(title,...text)=>({title,text});
function table(s){
 const R=root.SteelRoof,D=root.SteelRoofData,c=R.calc(s),members=R.memberInfo(s),kind=['brief','layout','deck-table'].includes(s.lesson)?'deck':['load-bridge','joist-table'].includes(s.lesson)?'joist':s.lesson==='girder-table'?'girder':'evidence';
 const result={title:kind==='evidence'?'Explain your whole load path':`Explain this ${kind} lookup`,focus:kind==='evidence'?'all':kind,lookupLesson:kind==='evidence'?null:kind+'-table',cards:[],question:'',status:'info',message:''};
 if(kind==='deck'){
  const pick=s.tablePick,span=pick?.span??c.deckSpan,gauge=pick?.gauge??s.gauge,cell=pick?R.deck[s.continuity][R.gauges.indexOf(gauge)][R.spans.indexOf(span)]:c.deckCell,match=!pick||(gauge===s.gauge&&span===c.deckSpan),n={single:1,double:2,triple:3}[s.continuity];
  result.source={kind:'deck',file:'Steel_Roof_Deck_Span_Load_Table.pdf',page:1};
  result.cards=[
   card(labels[0],`${s.family} ${s.option}: joists are ${f(c.spacing,3)} ft apart (${c.G} ft ÷ ${s.spaces} spaces). This is the deck span; ${c.L} ft is the joist span.`,`${s.continuity}-span deck: one sheet crosses ${n} span${n===1?'':'s'} and ${n+1} support lines. Total roof load is ${f(c.q)} psf; snow is ${c.live} psf.`),
   card(labels[1],`${s.continuity}-span block → ${s.gauge} ga row → ${c.deckSpan===undefined?'no listed span long enough':c.deckSpan+' ft column'}. Use the first listed span at or above ${f(c.spacing,3)} ft.`,pick?`Clicked cell: ${gauge} ga / ${span} ft.${match?' It matches the lookup conditions.':' This is a different column from the required lookup.'}`:'The PDF highlight is a lookup guide. Click the matching cell to record your reading.'),
   card(labels[2],cell?`${cell[0]} psf = allowable total uniform load. ${cell[1]} psf = load producing L/240 deflection. These are two load limits, not dimensions or material weights.`:'This source entry is blank or outside the listed spans. It supplies no load limits; blank does not mean zero.',cell&&match?`Compare ${f(c.q)} psf total with ${cell[0]} psf, and ${c.live} psf snow with ${cell[1]} psf. Keep the two comparisons separate.`:'Match the support condition, gauge and span before comparing loads.'),
   card(labels[3],`${s.gauge} ga sets ${R.thickness[s.gauge].toFixed(4)} in sheet thickness and ${R.weights[s.gauge]} psf deck self-weight. The Type-B profile stays 1.5 in deep.`,`${f(c.spacing,3)} ft remains the actual model span. ${c.deckSpan===undefined?'No displayed span column covers this spacing.':`Reading the ${c.deckSpan} ft table column does not move the joists.`} Gauge changes feed the roof load, joist line load and reactions; they do not change spacing.`)
  ];
  result.status=!cell||!match||!c.deckOK?'review':pick?'pass':'info';
  result.message=!match?'Recheck the clicked span column before using its values.':!cell?'No source value is available for this combination.':!c.deckOK?'A displayed load check is not satisfied. Revisit the gauge, continuity or spacing.':pick?'The two displayed deck checks are satisfied.':'The indicated cell covers the displayed loads. Read and select it in the PDF.';
  result.question='Why does your support arrangement lead to this block, row and column? Explain both psf values and which model dimension stays unchanged.';
 }
 if(kind==='joist'){
  const row=c.joist,m=members.joist,col=s.readColumn,defs={asd:[row.asd,'ASD allowable total line load','Compare with unfactored service load.'],lrfd:[row.lrfd,'LRFD factored total line-load capacity','This model shows service loads; do not compare them directly with LRFD.'],l240:[row.l240,'live line load at L/240 deflection','Compare with live load, not the total roof load.'],l360:[row.l360,'live line load at L/360 deflection','This is a stricter deflection criterion than L/240.'],weight:[row.weight,'joist self-weight','This is load carried by the joist, not its load capacity.']},selected=defs[col],names={asd:'ASD total load',lrfd:'LRFD total load',l240:'L/240 live load',l360:'L/360 live load',weight:'Weight'};
  result.source={kind:'joist',file:'Joist_Span_Load_Tables.pdf',page:D.joists[c.L].page};
  result.cards=[
   card(labels[0],`Nominal joist span: ${c.L} ft. Its tributary strip is ${f(c.spacing,3)} ft wide. ${f(c.q)} psf × ${f(c.spacing,3)} ft = ${f(c.wRoof,1)} plf roof load.`,`Add ${row.weight} plf joist self-weight once: ${f(c.wTotal,1)} plf total. Snow gives ${f(c.wLive,1)} plf live load.`),
   card(labels[1],`${c.L} ft span block → ${row.name} row → ${names[col]} column. The PDF highlight follows the column you click above the table.`,`For the displayed service checks, read ASD total load and the assigned live-load deflection column (currently L/${s.liveLimit}). Read Weight separately.`),
   card(labels[2],`${selected[0]} plf = ${selected[1]}. ${selected[2]}`,`Current checks: ${f(c.wTotal,1)} ${c.wTotal<=row.asd?'≤':'>'} ${row.asd} plf ASD; ${f(c.wLive,1)} ${c.wLive<=row['l'+s.liveLimit]?'≤':'>'} ${row['l'+s.liveLimit]} plf at L/${s.liveLimit}.`),
   card(labels[3],`${row.name}: ${m.depth} in nominal depth, ${m.series} series, section number ${m.section}. The 3D depth and designation follow the selected row.`,`Self-weight changes the total line load and the ${f(c.R)} kip end reaction passed to a girder. A new section number at the same depth changes table properties; chord/web sizes and web divisions remain schematic.`)
  ];
  result.status=col==='lrfd'||!c.joistOK?'review':'pass';result.message=col==='lrfd'?'The selected column uses LRFD. Return to ASD to compare the current service loads.':c.joistOK?'The displayed total-load and live-deflection checks are satisfied.':'This trial fails at least one displayed check. Explain which comparison governs before trying another row.';
  result.question=`Why is the ${c.L} ft block applicable? Explain the selected column's units, the governing check, and what ${row.name} changes in 3D.`;
 }
 if(kind==='girder'){
  const m=members.girder;
  result.source={kind:'girder',file:'Joist_Girder_Span_Load_Tables.pdf',page:D.girders[c.G].page};
  result.cards=[
   card(labels[0],`${c.G} ft girder span, ${s.spaces} equal spaces @ ${f(c.spacing,3)} ft. Joists arrive from ${s.sides===1?'one side':'two equal sides'}.`,`Each end reaction is ${f(c.R)} kips. Panel target = ${s.sides} × ${f(c.R)} + ${f(s.allowance,1)} kip assumed allowance = ${f(c.P)} kips per interior load point.`),
   card(labels[1],`${c.G} ft span block → ${s.spaces}-space group → ${s.girderDepth} in depth row → ${s.girderLoad} kip ASD column.`,c.gColumn===null?'The target exceeds every displayed ASD column.':`The first listed ASD column covering the target is ${c.gColumn} kips. The separate LRFD header uses a different load basis.`),
   card(labels[2],c.gWeight===null?'The clicked cell is blank: no estimated weight is supplied for this combination.':`${c.gWeight} plf = estimated girder self-weight per foot. It is not a ${c.gWeight} kip capacity.`,`The ${s.girderLoad} kip column is the designated load per interior panel point, including the stated allowance. A weight-table entry does not verify strength, deflection or connections.`),
   card(labels[3],`${m.name}: ${m.depth} in depth; G = joist girder; ${m.spaces}N = joist spaces; ${m.load}K = ASD kips per load point. K here means kips.`,`${m.spaces} spaces give ${m.joistLines} joist lines and ${m.interiorPoints} interior load points. Depth and load-point positions follow these inputs. Webs and chord sections are schematic; a different load column does not supply an exact cross-section.`)
  ];
  result.status=c.gWeight!==null&&s.girderLoad>=c.P&&c.joistOK?'info':'review';result.message=c.gWeight===null?'Blank cell: revise the row or column; do not treat this as zero weight.':s.girderLoad<c.P?'The selected panel-load column is below the target.':!c.joistOK?'This column covers the panel target, but the upstream joist trial still needs revision.':'This column covers the stated panel target and supplies a preliminary weight estimate. Girder design still needs verification.';
  result.question='Explain why this space group and load column fit your model. What does the cell in plf tell you, and which parts of the designation control geometry?';
 }
 if(kind==='evidence'){
  result.cards=[card(labels[0],`${s.family} ${s.option}: deck spans ${f(c.spacing,3)} ft between joists; joists span ${c.L} ft; girders span ${c.G} ft.`,`${c.live} psf snow + 15 psf roofing + ${R.weights[s.gauge]} psf deck = ${f(c.q)} psf before joist self-weight.`),card(labels[1],`Deck: ${s.continuity} / ${s.gauge} ga / ${c.deckSpan??'beyond table'} ft. Joist: ${c.L} ft / ${s.joist}. Girder: ${c.G} ft / ${s.spaces} spaces / ${s.girderDepth} in / ${s.girderLoad} kip ASD.`,`Keep each PDF filename, page, block, row and column with your own study record.`),card(labels[2],'Deck cells contain psf load limits. Joist columns contain plf capacities, deflection limits or self-weight. Girder cells contain estimated self-weight in plf.',`A matching number only has meaning when the span, supports, units and load basis also match.`),card(labels[3],`Carry ${R.thickness[s.gauge].toFixed(4)} in deck sheet thickness, ${members.joist.depth} in joist depth, ${s.girderDepth} in girder depth and ${f(c.spacing,3)} ft spacing into your own Revit model.`,`Check actual roof slopes, bearings and extensions separately. This nominal bay and the schematic webs do not supply a complete Revit family or verified design.`)];
  result.message=`Deck: ${c.deckOK?'displayed load checks satisfied':'recheck'}. Joist: ${c.joistOK?'displayed load checks satisfied':'recheck'}. Girder: ${c.gWeight!==null&&s.girderLoad>=c.P?'preliminary weight entry available':'recheck row/column'}.`;
  result.question='In your own words, connect one model condition to an original table location, explain the value and units, and identify what you will model from it.';
 }
 return result;
}
function concept(s){
 const S=root.SteelReflection,l=S.lessons.find(x=>x.id===s.lesson),r={title:'Explain what you observe',cards:[],question:l.prompt,status:'info',message:'This concept model explains a relationship. It does not select project members.'};
 if(s.lesson==='material'){
  const m=S.materialState(s);r.cards=[card('Model condition',`Applied load: ${s.materialLoad}% of the model yield load. Highest applied load: ${s.materialPeak}%.`),card('What to read','Course Lecture 9, PDF pp. 13–21: stress, strain, elastic behavior and plastic behavior.'),card('What it means',m.residual?'The specimen has passed yield. Unloading removes elastic strain but leaves permanent strain.':'The specimen has not passed yield. Unloading removes the elastic strain in this idealized model.'),card('What changes in the model','Load and unload to compare the specimen with its original outline. Deformation is enlarged. The percentages describe this demonstration, not a specified steel grade.')];
 }else if(s.lesson==='anatomy'){
  const t=S.terms[s.part];r.cards=[card('Model condition',`${t.name} · ${t.role}.`,t.text),card('Connect to the source',`Course Lecture 9, PDF pp. ${l.pages}. Follow deck → joists → girders → columns, then identify the supporting element in the model.`),card('What it means','A member name identifies a structural role. Depth, gauge, section number, bearing location and bridging describe different properties; they are not interchangeable.'),card('What changes in the model','Select a term or click a component to identify its position. Joist close-up reveals chords, webs and seats. Deck profile separates profile depth from sheet thickness. Exact sizes are queried in Lecture 1.1.')];
 }else if(s.lesson==='spans'){
  const c=S.scene(s);r.cards=[card('Model condition',`Concept bay: 24 × 36 ft. Joist span ${c.span} ft; girder span ${c.girderSpan} ft; ${s.spaces} equal spaces.`),card('Connect to a table',`${c.girderSpan} ft ÷ ${s.spaces} spaces = ${f(c.spacing,3)} ft deck span. The deck table uses this support distance. The joist table uses the ${c.span} ft length along the joist.`),card('What it means','Span runs along a member between its supports. Spacing runs across adjacent members and defines the tributary width of an interior joist.'),card('What changes in the model',`${s.spaces} spaces create ${c.count} joist lines. More spaces shorten deck span and tributary width while increasing member count. Depths stay fixed in this concept experiment; your Lecture 1.1 assignment remains separate.`)];
 }else if(s.lesson==='loads'){
  const stages=['Deck area load','Joist line load','Joist end reaction','Column reaction'];r.cards=[card('Model condition',`Current load-path stage: ${stages[s.loadStage]}. The highlighted member receives load from the elements above it.`),card('Connect to the table headings','Deck: psf. Joist: plf. Girder input: kips per load point; girder output: estimated weight in plf.'),card('What it means','psf × tributary width in ft = plf. For a simply supported joist with uniform line load, wL/2 gives each end reaction. Divide pounds by 1,000 for kips.'),card('What changes in the model','Follow the arrows from area to line to discrete reactions. Receiving joists from both sides increases the girder panel load; it does not double the girder span.')];
 }else{
  const step=S.steps[s.step];r.cards=[card('Current decision',step[0],step[1]),card('Find your evidence',step[2],'Course Lecture 9, PDF pp. '+l.pages+'.'),card('What it means','A project decision needs matching geometry, support conditions and source units. Record the evidence and any unresolved checks in your own words.'),card('Apply it in your model','Use Lecture 1.1 to read the original tables. Then build your own Revit model with the assigned families, checking directions, dimensions and bearing elevations.')];
 }
 return r;
}
function html(r){return `<section class="se-explanation"><p class="se-live">Follows your current model and selection</p><h2>${esc(r.title)}</h2><ol class="se-chain">${r.cards.map((c,i)=>`<li><span class="se-number">${i+1}</span><div><h3>${esc(c.title)}</h3>${c.text.map(t=>`<p>${esc(t)}</p>`).join('')}${i===1&&r.source?`<a class="se-source" href="${root.SteelPDFTables.url(r.source.kind,r.source.page)}" target="_blank" rel="noopener">${esc(r.source.file)} · PDF p. ${r.source.page} ↗</a>`:''}</div></li>`).join('')}</ol><p class="se-verdict se-${r.status}">${esc(r.message)}</p>${r.lookupLesson?`<div class="se-actions"><button data-explain-model="${r.focus}">Show the ${r.focus} in 3D</button><button data-explain-lookup="${r.lookupLesson}">Locate the PDF row / cell</button></div>`:''}<div class="se-question"><h3>Explain your choice</h3><p>${esc(r.question)}</p><small>Use the reflection box below. Your explanation stays editable.</small></div></section>`;}
function tabs(panel){return `<div class="steel-panel-tabs" role="tablist" aria-label="Steel lesson panels">${['model','explain'].map(p=>`<button id="steel-${p}-tab" type="button" role="tab" data-steel-panel="${p}" aria-controls="steel-${p}-panel" aria-selected="${panel===p}" tabindex="${panel===p?0:-1}">${p==='model'?'Model':'Explain'}</button>`).join('')}</div>`;}
function bindTabs(el,s){const buttons=[...el.querySelectorAll('[data-steel-panel]')];const select=panel=>{s.panel=panel;buttons.forEach(b=>{const active=b.dataset.steelPanel===panel;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});for(const p of ['model','explain']){const box=el.querySelector('#steel-'+p+'-panel');if(box)box.hidden=p!==panel;}};for(const b of buttons){b.onclick=()=>select(b.dataset.steelPanel);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?buttons[0]:e.key==='End'?buttons[1]:buttons.find(x=>x!==b);select(next.dataset.steelPanel);next.focus();};}}
root.SteelExplain={table,concept,html,tabs,bindTabs};
})(window);
